[workspace]

members = [
    "crates/*",
    "apps/core/src-tauri"
]
resolver = "2"

[workspace.package]
name = "tablex" 
description = "Table Viewer for modern developers"
version = "0.3.4"    
license = "MIT"
authors = ["Kareem Ebrahim <kareemmahlees@gmail.com>"]
repository = "https://github.com/kareemmahlees/tablex"
rust-version = "1.60"
edition = "2021"


[workspace.profile.release]
panic = "abort" 
codegen-units = 1 
lto = true 
opt-level = "s" 
strip = true 

[workspace.dependencies]
tauri = { version = "1.6.1", features = [ "shell-open", "os-all", "clipboard-write-text", "global-shortcut-all", "dialog-open", "test", "process-command-api"] }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
uuid = {version = "1.6.1",features = ["v4", "fast-rng", "macro-diagnostics"] }
sqlx = { version = "0.7.4", features = [ "runtime-tokio", "tls-native-tls", "sqlite", "postgres", "mysql", "time"] }

