/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsLayoutRouteImport } from './routes/_settings-layout'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as ConnectionConnIdTableLayoutRouteImport } from './routes/connection.$connId/_table-layout'
import { Route as SettingsLayoutSettingsPreferencesRouteRouteImport } from './routes/_settings-layout.settings/preferences/route'
import { Route as ConnectionConnIdTableLayoutUtilitiesRouteRouteImport } from './routes/connection.$connId/_table-layout/utilities/route'
import { Route as ConnectionConnIdTableLayoutSqlEditorRouteRouteImport } from './routes/connection.$connId/_table-layout/sql-editor/route'
import { Route as ConnectionConnIdTableLayoutTableViewEmptyRouteRouteImport } from './routes/connection.$connId/_table-layout/table-view/empty/route'
import { Route as ConnectionConnIdTableLayoutTableViewTableNameRouteRouteImport } from './routes/connection.$connId/_table-layout/table-view/$tableName/route'

const SettingsLayoutRoute = SettingsLayoutRouteImport.update({
  id: '/_settings-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionConnIdTableLayoutRoute =
  ConnectionConnIdTableLayoutRouteImport.update({
    id: '/connection/$connId/_table-layout',
    path: '/connection/$connId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsLayoutSettingsPreferencesRouteRoute =
  SettingsLayoutSettingsPreferencesRouteRouteImport.update({
    id: '/settings/preferences',
    path: '/settings/preferences',
    getParentRoute: () => SettingsLayoutRoute,
  } as any)
const ConnectionConnIdTableLayoutUtilitiesRouteRoute =
  ConnectionConnIdTableLayoutUtilitiesRouteRouteImport.update({
    id: '/utilities',
    path: '/utilities',
    getParentRoute: () => ConnectionConnIdTableLayoutRoute,
  } as any)
const ConnectionConnIdTableLayoutSqlEditorRouteRoute =
  ConnectionConnIdTableLayoutSqlEditorRouteRouteImport.update({
    id: '/sql-editor',
    path: '/sql-editor',
    getParentRoute: () => ConnectionConnIdTableLayoutRoute,
  } as any)
const ConnectionConnIdTableLayoutTableViewEmptyRouteRoute =
  ConnectionConnIdTableLayoutTableViewEmptyRouteRouteImport.update({
    id: '/table-view/empty',
    path: '/table-view/empty',
    getParentRoute: () => ConnectionConnIdTableLayoutRoute,
  } as any)
const ConnectionConnIdTableLayoutTableViewTableNameRouteRoute =
  ConnectionConnIdTableLayoutTableViewTableNameRouteRouteImport.update({
    id: '/table-view/$tableName',
    path: '/table-view/$tableName',
    getParentRoute: () => ConnectionConnIdTableLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SettingsLayoutRouteWithChildren
  '/settings/preferences': typeof SettingsLayoutSettingsPreferencesRouteRoute
  '/connection/$connId': typeof ConnectionConnIdTableLayoutRouteWithChildren
  '/connection/$connId/sql-editor': typeof ConnectionConnIdTableLayoutSqlEditorRouteRoute
  '/connection/$connId/utilities': typeof ConnectionConnIdTableLayoutUtilitiesRouteRoute
  '/connection/$connId/table-view/$tableName': typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRoute
  '/connection/$connId/table-view/empty': typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof SettingsLayoutRouteWithChildren
  '/settings/preferences': typeof SettingsLayoutSettingsPreferencesRouteRoute
  '/connection/$connId': typeof ConnectionConnIdTableLayoutRouteWithChildren
  '/connection/$connId/sql-editor': typeof ConnectionConnIdTableLayoutSqlEditorRouteRoute
  '/connection/$connId/utilities': typeof ConnectionConnIdTableLayoutUtilitiesRouteRoute
  '/connection/$connId/table-view/$tableName': typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRoute
  '/connection/$connId/table-view/empty': typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/_settings-layout': typeof SettingsLayoutRouteWithChildren
  '/_settings-layout/settings/preferences': typeof SettingsLayoutSettingsPreferencesRouteRoute
  '/connection/$connId/_table-layout': typeof ConnectionConnIdTableLayoutRouteWithChildren
  '/connection/$connId/_table-layout/sql-editor': typeof ConnectionConnIdTableLayoutSqlEditorRouteRoute
  '/connection/$connId/_table-layout/utilities': typeof ConnectionConnIdTableLayoutUtilitiesRouteRoute
  '/connection/$connId/_table-layout/table-view/$tableName': typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRoute
  '/connection/$connId/_table-layout/table-view/empty': typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings/preferences'
    | '/connection/$connId'
    | '/connection/$connId/sql-editor'
    | '/connection/$connId/utilities'
    | '/connection/$connId/table-view/$tableName'
    | '/connection/$connId/table-view/empty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/preferences'
    | '/connection/$connId'
    | '/connection/$connId/sql-editor'
    | '/connection/$connId/utilities'
    | '/connection/$connId/table-view/$tableName'
    | '/connection/$connId/table-view/empty'
  id:
    | '__root__'
    | '/'
    | '/_settings-layout'
    | '/_settings-layout/settings/preferences'
    | '/connection/$connId/_table-layout'
    | '/connection/$connId/_table-layout/sql-editor'
    | '/connection/$connId/_table-layout/utilities'
    | '/connection/$connId/_table-layout/table-view/$tableName'
    | '/connection/$connId/_table-layout/table-view/empty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  SettingsLayoutRoute: typeof SettingsLayoutRouteWithChildren
  ConnectionConnIdTableLayoutRoute: typeof ConnectionConnIdTableLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_settings-layout': {
      id: '/_settings-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SettingsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection/$connId/_table-layout': {
      id: '/connection/$connId/_table-layout'
      path: '/connection/$connId'
      fullPath: '/connection/$connId'
      preLoaderRoute: typeof ConnectionConnIdTableLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_settings-layout/settings/preferences': {
      id: '/_settings-layout/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsLayoutSettingsPreferencesRouteRouteImport
      parentRoute: typeof SettingsLayoutRoute
    }
    '/connection/$connId/_table-layout/utilities': {
      id: '/connection/$connId/_table-layout/utilities'
      path: '/utilities'
      fullPath: '/connection/$connId/utilities'
      preLoaderRoute: typeof ConnectionConnIdTableLayoutUtilitiesRouteRouteImport
      parentRoute: typeof ConnectionConnIdTableLayoutRoute
    }
    '/connection/$connId/_table-layout/sql-editor': {
      id: '/connection/$connId/_table-layout/sql-editor'
      path: '/sql-editor'
      fullPath: '/connection/$connId/sql-editor'
      preLoaderRoute: typeof ConnectionConnIdTableLayoutSqlEditorRouteRouteImport
      parentRoute: typeof ConnectionConnIdTableLayoutRoute
    }
    '/connection/$connId/_table-layout/table-view/empty': {
      id: '/connection/$connId/_table-layout/table-view/empty'
      path: '/table-view/empty'
      fullPath: '/connection/$connId/table-view/empty'
      preLoaderRoute: typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRouteImport
      parentRoute: typeof ConnectionConnIdTableLayoutRoute
    }
    '/connection/$connId/_table-layout/table-view/$tableName': {
      id: '/connection/$connId/_table-layout/table-view/$tableName'
      path: '/table-view/$tableName'
      fullPath: '/connection/$connId/table-view/$tableName'
      preLoaderRoute: typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRouteImport
      parentRoute: typeof ConnectionConnIdTableLayoutRoute
    }
  }
}

interface SettingsLayoutRouteChildren {
  SettingsLayoutSettingsPreferencesRouteRoute: typeof SettingsLayoutSettingsPreferencesRouteRoute
}

const SettingsLayoutRouteChildren: SettingsLayoutRouteChildren = {
  SettingsLayoutSettingsPreferencesRouteRoute:
    SettingsLayoutSettingsPreferencesRouteRoute,
}

const SettingsLayoutRouteWithChildren = SettingsLayoutRoute._addFileChildren(
  SettingsLayoutRouteChildren,
)

interface ConnectionConnIdTableLayoutRouteChildren {
  ConnectionConnIdTableLayoutSqlEditorRouteRoute: typeof ConnectionConnIdTableLayoutSqlEditorRouteRoute
  ConnectionConnIdTableLayoutUtilitiesRouteRoute: typeof ConnectionConnIdTableLayoutUtilitiesRouteRoute
  ConnectionConnIdTableLayoutTableViewTableNameRouteRoute: typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRoute
  ConnectionConnIdTableLayoutTableViewEmptyRouteRoute: typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRoute
}

const ConnectionConnIdTableLayoutRouteChildren: ConnectionConnIdTableLayoutRouteChildren =
  {
    ConnectionConnIdTableLayoutSqlEditorRouteRoute:
      ConnectionConnIdTableLayoutSqlEditorRouteRoute,
    ConnectionConnIdTableLayoutUtilitiesRouteRoute:
      ConnectionConnIdTableLayoutUtilitiesRouteRoute,
    ConnectionConnIdTableLayoutTableViewTableNameRouteRoute:
      ConnectionConnIdTableLayoutTableViewTableNameRouteRoute,
    ConnectionConnIdTableLayoutTableViewEmptyRouteRoute:
      ConnectionConnIdTableLayoutTableViewEmptyRouteRoute,
  }

const ConnectionConnIdTableLayoutRouteWithChildren =
  ConnectionConnIdTableLayoutRoute._addFileChildren(
    ConnectionConnIdTableLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  SettingsLayoutRoute: SettingsLayoutRouteWithChildren,
  ConnectionConnIdTableLayoutRoute:
    ConnectionConnIdTableLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
