/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectionConnIdRouteRouteImport } from './routes/connection.$connId/route'
import { Route as ConnectionConnIdSqlRouteImport } from './routes/connection.$connId/sql'
import { Route as ConnectionConnIdEditorRouteImport } from './routes/connection.$connId/editor'
import { Route as ConnectionConnIdSettingsRouteRouteImport } from './routes/connection.$connId/settings/route'
import { Route as ConnectionConnIdSettingsIndexRouteImport } from './routes/connection.$connId/settings/index'
import { Route as ConnectionConnIdTableLayoutUtilitiesRouteRouteImport } from './routes/connection.$connId/_table-layout/utilities/route'
import { Route as ConnectionConnIdTableLayoutSqlEditorRouteRouteImport } from './routes/connection.$connId/_table-layout/sql-editor/route'
import { Route as ConnectionConnIdTableLayoutTableViewEmptyRouteRouteImport } from './routes/connection.$connId/_table-layout/table-view/empty/route'
import { Route as ConnectionConnIdTableLayoutTableViewTableNameRouteRouteImport } from './routes/connection.$connId/_table-layout/table-view/$tableName/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionConnIdRouteRoute = ConnectionConnIdRouteRouteImport.update({
  id: '/connection/$connId',
  path: '/connection/$connId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionConnIdSqlRoute = ConnectionConnIdSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => ConnectionConnIdRouteRoute,
} as any)
const ConnectionConnIdEditorRoute = ConnectionConnIdEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => ConnectionConnIdRouteRoute,
} as any)
const ConnectionConnIdSettingsRouteRoute =
  ConnectionConnIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ConnectionConnIdRouteRoute,
  } as any)
const ConnectionConnIdSettingsIndexRoute =
  ConnectionConnIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectionConnIdSettingsRouteRoute,
  } as any)
const ConnectionConnIdTableLayoutUtilitiesRouteRoute =
  ConnectionConnIdTableLayoutUtilitiesRouteRouteImport.update({
    id: '/_table-layout/utilities',
    path: '/utilities',
    getParentRoute: () => ConnectionConnIdRouteRoute,
  } as any)
const ConnectionConnIdTableLayoutSqlEditorRouteRoute =
  ConnectionConnIdTableLayoutSqlEditorRouteRouteImport.update({
    id: '/_table-layout/sql-editor',
    path: '/sql-editor',
    getParentRoute: () => ConnectionConnIdRouteRoute,
  } as any)
const ConnectionConnIdTableLayoutTableViewEmptyRouteRoute =
  ConnectionConnIdTableLayoutTableViewEmptyRouteRouteImport.update({
    id: '/_table-layout/table-view/empty',
    path: '/table-view/empty',
    getParentRoute: () => ConnectionConnIdRouteRoute,
  } as any)
const ConnectionConnIdTableLayoutTableViewTableNameRouteRoute =
  ConnectionConnIdTableLayoutTableViewTableNameRouteRouteImport.update({
    id: '/_table-layout/table-view/$tableName',
    path: '/table-view/$tableName',
    getParentRoute: () => ConnectionConnIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connection/$connId': typeof ConnectionConnIdRouteRouteWithChildren
  '/connection/$connId/settings': typeof ConnectionConnIdSettingsRouteRouteWithChildren
  '/connection/$connId/editor': typeof ConnectionConnIdEditorRoute
  '/connection/$connId/sql': typeof ConnectionConnIdSqlRoute
  '/connection/$connId/sql-editor': typeof ConnectionConnIdTableLayoutSqlEditorRouteRoute
  '/connection/$connId/utilities': typeof ConnectionConnIdTableLayoutUtilitiesRouteRoute
  '/connection/$connId/settings/': typeof ConnectionConnIdSettingsIndexRoute
  '/connection/$connId/table-view/$tableName': typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRoute
  '/connection/$connId/table-view/empty': typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connection/$connId': typeof ConnectionConnIdRouteRouteWithChildren
  '/connection/$connId/editor': typeof ConnectionConnIdEditorRoute
  '/connection/$connId/sql': typeof ConnectionConnIdSqlRoute
  '/connection/$connId/sql-editor': typeof ConnectionConnIdTableLayoutSqlEditorRouteRoute
  '/connection/$connId/utilities': typeof ConnectionConnIdTableLayoutUtilitiesRouteRoute
  '/connection/$connId/settings': typeof ConnectionConnIdSettingsIndexRoute
  '/connection/$connId/table-view/$tableName': typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRoute
  '/connection/$connId/table-view/empty': typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connection/$connId': typeof ConnectionConnIdRouteRouteWithChildren
  '/connection/$connId/settings': typeof ConnectionConnIdSettingsRouteRouteWithChildren
  '/connection/$connId/editor': typeof ConnectionConnIdEditorRoute
  '/connection/$connId/sql': typeof ConnectionConnIdSqlRoute
  '/connection/$connId/_table-layout/sql-editor': typeof ConnectionConnIdTableLayoutSqlEditorRouteRoute
  '/connection/$connId/_table-layout/utilities': typeof ConnectionConnIdTableLayoutUtilitiesRouteRoute
  '/connection/$connId/settings/': typeof ConnectionConnIdSettingsIndexRoute
  '/connection/$connId/_table-layout/table-view/$tableName': typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRoute
  '/connection/$connId/_table-layout/table-view/empty': typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connection/$connId'
    | '/connection/$connId/settings'
    | '/connection/$connId/editor'
    | '/connection/$connId/sql'
    | '/connection/$connId/sql-editor'
    | '/connection/$connId/utilities'
    | '/connection/$connId/settings/'
    | '/connection/$connId/table-view/$tableName'
    | '/connection/$connId/table-view/empty'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connection/$connId'
    | '/connection/$connId/editor'
    | '/connection/$connId/sql'
    | '/connection/$connId/sql-editor'
    | '/connection/$connId/utilities'
    | '/connection/$connId/settings'
    | '/connection/$connId/table-view/$tableName'
    | '/connection/$connId/table-view/empty'
  id:
    | '__root__'
    | '/'
    | '/connection/$connId'
    | '/connection/$connId/settings'
    | '/connection/$connId/editor'
    | '/connection/$connId/sql'
    | '/connection/$connId/_table-layout/sql-editor'
    | '/connection/$connId/_table-layout/utilities'
    | '/connection/$connId/settings/'
    | '/connection/$connId/_table-layout/table-view/$tableName'
    | '/connection/$connId/_table-layout/table-view/empty'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionConnIdRouteRoute: typeof ConnectionConnIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection/$connId': {
      id: '/connection/$connId'
      path: '/connection/$connId'
      fullPath: '/connection/$connId'
      preLoaderRoute: typeof ConnectionConnIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connection/$connId/sql': {
      id: '/connection/$connId/sql'
      path: '/sql'
      fullPath: '/connection/$connId/sql'
      preLoaderRoute: typeof ConnectionConnIdSqlRouteImport
      parentRoute: typeof ConnectionConnIdRouteRoute
    }
    '/connection/$connId/editor': {
      id: '/connection/$connId/editor'
      path: '/editor'
      fullPath: '/connection/$connId/editor'
      preLoaderRoute: typeof ConnectionConnIdEditorRouteImport
      parentRoute: typeof ConnectionConnIdRouteRoute
    }
    '/connection/$connId/settings': {
      id: '/connection/$connId/settings'
      path: '/settings'
      fullPath: '/connection/$connId/settings'
      preLoaderRoute: typeof ConnectionConnIdSettingsRouteRouteImport
      parentRoute: typeof ConnectionConnIdRouteRoute
    }
    '/connection/$connId/settings/': {
      id: '/connection/$connId/settings/'
      path: '/'
      fullPath: '/connection/$connId/settings/'
      preLoaderRoute: typeof ConnectionConnIdSettingsIndexRouteImport
      parentRoute: typeof ConnectionConnIdSettingsRouteRoute
    }
    '/connection/$connId/_table-layout/utilities': {
      id: '/connection/$connId/_table-layout/utilities'
      path: '/utilities'
      fullPath: '/connection/$connId/utilities'
      preLoaderRoute: typeof ConnectionConnIdTableLayoutUtilitiesRouteRouteImport
      parentRoute: typeof ConnectionConnIdRouteRoute
    }
    '/connection/$connId/_table-layout/sql-editor': {
      id: '/connection/$connId/_table-layout/sql-editor'
      path: '/sql-editor'
      fullPath: '/connection/$connId/sql-editor'
      preLoaderRoute: typeof ConnectionConnIdTableLayoutSqlEditorRouteRouteImport
      parentRoute: typeof ConnectionConnIdRouteRoute
    }
    '/connection/$connId/_table-layout/table-view/empty': {
      id: '/connection/$connId/_table-layout/table-view/empty'
      path: '/table-view/empty'
      fullPath: '/connection/$connId/table-view/empty'
      preLoaderRoute: typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRouteImport
      parentRoute: typeof ConnectionConnIdRouteRoute
    }
    '/connection/$connId/_table-layout/table-view/$tableName': {
      id: '/connection/$connId/_table-layout/table-view/$tableName'
      path: '/table-view/$tableName'
      fullPath: '/connection/$connId/table-view/$tableName'
      preLoaderRoute: typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRouteImport
      parentRoute: typeof ConnectionConnIdRouteRoute
    }
  }
}

interface ConnectionConnIdSettingsRouteRouteChildren {
  ConnectionConnIdSettingsIndexRoute: typeof ConnectionConnIdSettingsIndexRoute
}

const ConnectionConnIdSettingsRouteRouteChildren: ConnectionConnIdSettingsRouteRouteChildren =
  {
    ConnectionConnIdSettingsIndexRoute: ConnectionConnIdSettingsIndexRoute,
  }

const ConnectionConnIdSettingsRouteRouteWithChildren =
  ConnectionConnIdSettingsRouteRoute._addFileChildren(
    ConnectionConnIdSettingsRouteRouteChildren,
  )

interface ConnectionConnIdRouteRouteChildren {
  ConnectionConnIdSettingsRouteRoute: typeof ConnectionConnIdSettingsRouteRouteWithChildren
  ConnectionConnIdEditorRoute: typeof ConnectionConnIdEditorRoute
  ConnectionConnIdSqlRoute: typeof ConnectionConnIdSqlRoute
  ConnectionConnIdTableLayoutSqlEditorRouteRoute: typeof ConnectionConnIdTableLayoutSqlEditorRouteRoute
  ConnectionConnIdTableLayoutUtilitiesRouteRoute: typeof ConnectionConnIdTableLayoutUtilitiesRouteRoute
  ConnectionConnIdTableLayoutTableViewTableNameRouteRoute: typeof ConnectionConnIdTableLayoutTableViewTableNameRouteRoute
  ConnectionConnIdTableLayoutTableViewEmptyRouteRoute: typeof ConnectionConnIdTableLayoutTableViewEmptyRouteRoute
}

const ConnectionConnIdRouteRouteChildren: ConnectionConnIdRouteRouteChildren = {
  ConnectionConnIdSettingsRouteRoute:
    ConnectionConnIdSettingsRouteRouteWithChildren,
  ConnectionConnIdEditorRoute: ConnectionConnIdEditorRoute,
  ConnectionConnIdSqlRoute: ConnectionConnIdSqlRoute,
  ConnectionConnIdTableLayoutSqlEditorRouteRoute:
    ConnectionConnIdTableLayoutSqlEditorRouteRoute,
  ConnectionConnIdTableLayoutUtilitiesRouteRoute:
    ConnectionConnIdTableLayoutUtilitiesRouteRoute,
  ConnectionConnIdTableLayoutTableViewTableNameRouteRoute:
    ConnectionConnIdTableLayoutTableViewTableNameRouteRoute,
  ConnectionConnIdTableLayoutTableViewEmptyRouteRoute:
    ConnectionConnIdTableLayoutTableViewEmptyRouteRoute,
}

const ConnectionConnIdRouteRouteWithChildren =
  ConnectionConnIdRouteRoute._addFileChildren(
    ConnectionConnIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionConnIdRouteRoute: ConnectionConnIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
