[package]
name = "table_x"
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
default-run = "table_x"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
tx_lib = { path = "../../../crates/lib" }
tx_handlers = { path = "../../../crates/handlers" }
serde_json = { workspace = true }
serde = { workspace = true }
tauri = { version = "1.6.1", features = [
    "shell-open",
    "os-all",
    "clipboard-write-text",
    "global-shortcut-all",
    "dialog-open",
    "test",
    "process-command-api",
] }
sqlx = { workspace = true }
clap = { version = "4.5.1", features = ["derive"] }
tokio = { workspace = true }
regex = "1.10.3"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[target."cfg(windows)".dependencies]
windows = { version = "0.54.0", features = [
    "Win32_System_Console",
    "Win32_Foundation",
] }
