#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


if ! git diff --cached --quiet HEAD -- "package.json" "apps\/core\/**" "packages\/**";
then
    bun --filter @tablex/core lint
fi

if ! git diff --cached --quiet HEAD --  "**\/Cargo.toml"  "**\/Cargo.lock"  "**\/*.rs";
then
    bun rust:lint
fi

if ! git diff --cached --quiet HEAD --  "package.json"  "apps\/web\/**"  "packages\/**";
then
    bun astro:check
fi

exit 0