/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ConnectionsRouteImport } from './routes/connections/route'
import { Route as ConnectRouteImport } from './routes/connect/route'
import { Route as IndexRouteImport } from './routes/index/route'
import { Route as DashboardLayoutImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutSettingsRouteImport } from './routes/dashboard/_layout/settings/route'
import { Route as DashboardLayoutKeybindingsRouteImport } from './routes/dashboard/_layout/keybindings/route'
import { Route as DashboardLayoutApiDocsRouteImport } from './routes/dashboard/_layout/api-docs/route'
import { Route as DashboardLayoutTableViewLandRouteImport } from './routes/dashboard/_layout/table-view/land/route'
import { Route as DashboardLayoutTableViewTableNameRouteImport } from './routes/dashboard/_layout/table-view/$tableName/route'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ConnectionsRouteRoute = ConnectionsRouteImport.update({
  path: '/connections',
  getParentRoute: () => rootRoute,
} as any)

const ConnectRouteRoute = ConnectRouteImport.update({
  path: '/connect',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardLayoutRoute = DashboardLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardLayoutSettingsRouteRoute =
  DashboardLayoutSettingsRouteImport.update({
    path: '/settings',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutKeybindingsRouteRoute =
  DashboardLayoutKeybindingsRouteImport.update({
    path: '/keybindings',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutApiDocsRouteRoute =
  DashboardLayoutApiDocsRouteImport.update({
    path: '/api-docs',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutTableViewLandRouteRoute =
  DashboardLayoutTableViewLandRouteImport.update({
    path: '/table-view/land',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

const DashboardLayoutTableViewTableNameRouteRoute =
  DashboardLayoutTableViewTableNameRouteImport.update({
    path: '/table-view/$tableName',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRoute
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_layout/api-docs': {
      id: '/dashboard/_layout/api-docs'
      path: '/api-docs'
      fullPath: '/dashboard/api-docs'
      preLoaderRoute: typeof DashboardLayoutApiDocsRouteImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/keybindings': {
      id: '/dashboard/_layout/keybindings'
      path: '/keybindings'
      fullPath: '/dashboard/keybindings'
      preLoaderRoute: typeof DashboardLayoutKeybindingsRouteImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/settings': {
      id: '/dashboard/_layout/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardLayoutSettingsRouteImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/table-view/$tableName': {
      id: '/dashboard/_layout/table-view/$tableName'
      path: '/table-view/$tableName'
      fullPath: '/dashboard/table-view/$tableName'
      preLoaderRoute: typeof DashboardLayoutTableViewTableNameRouteImport
      parentRoute: typeof DashboardLayoutImport
    }
    '/dashboard/_layout/table-view/land': {
      id: '/dashboard/_layout/table-view/land'
      path: '/table-view/land'
      fullPath: '/dashboard/table-view/land'
      preLoaderRoute: typeof DashboardLayoutTableViewLandRouteImport
      parentRoute: typeof DashboardLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  ConnectRouteRoute,
  ConnectionsRouteRoute,
  DashboardRoute: DashboardRoute.addChildren({
    DashboardLayoutRoute: DashboardLayoutRoute.addChildren({
      DashboardLayoutApiDocsRouteRoute,
      DashboardLayoutKeybindingsRouteRoute,
      DashboardLayoutSettingsRouteRoute,
      DashboardLayoutTableViewTableNameRouteRoute,
      DashboardLayoutTableViewLandRouteRoute,
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/connect",
        "/connections",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index/route.tsx"
    },
    "/connect": {
      "filePath": "connect/route.tsx"
    },
    "/connections": {
      "filePath": "connections/route.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_layout"
      ]
    },
    "/dashboard/_layout": {
      "filePath": "dashboard/_layout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_layout/api-docs",
        "/dashboard/_layout/keybindings",
        "/dashboard/_layout/settings",
        "/dashboard/_layout/table-view/$tableName",
        "/dashboard/_layout/table-view/land"
      ]
    },
    "/dashboard/_layout/api-docs": {
      "filePath": "dashboard/_layout/api-docs/route.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/keybindings": {
      "filePath": "dashboard/_layout/keybindings/route.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/settings": {
      "filePath": "dashboard/_layout/settings/route.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/table-view/$tableName": {
      "filePath": "dashboard/_layout/table-view/$tableName/route.tsx",
      "parent": "/dashboard/_layout"
    },
    "/dashboard/_layout/table-view/land": {
      "filePath": "dashboard/_layout/table-view/land/route.tsx",
      "parent": "/dashboard/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
