name: Astro Build Status

on:
  push:
    branches:
      - master
    paths:
      - "apps/web/**"
      - "packages"
      - "package.json"
  pull_request:
    branches:
      - master
    paths:
      - "apps/web/**"
      - "packages"
      - "package.json"
  workflow_dispatch:

jobs:
  astro-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            apps/web
            apps/core/package.json
            packages

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lock

      - name: Run Astro build
        run: bun astro:build
