name: Changeset

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  HUSKY: 0

jobs:
  version-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lock

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          title: "chore: version pump 🔖"
          commit: "chore: version pump 🔖"
          publish: bunx changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
