name: Tauri Build Status

on:
  push:
    branches:
      - master
    paths:
      - "apps/core/**"
      - "crates"
      - "packages"
      - "package.json"
  pull_request:
    branches:
      - master
    paths:
      - "apps/core/**"
      - "crates"
      - "packages"
      - "package.json"
  workflow_dispatch:

env:
  HUSKY: 0
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0 # This would add unnecessary bloat to the target folder, decreasing cache efficiency.

jobs:
  tauri-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            target: "aarch64-apple-darwin"

          - platform: "macos-latest"
            target: "x86_64-apple-darwin"

          # - platform: "ubuntu-22.04"
          #   target: "aarch64-unknown-linux-gnu"

          - platform: "ubuntu-22.04"
            target: "x86_64-unknown-linux-gnu"

          - platform: "windows-latest"
            target: "aarch64-pc-windows-msvc"

          - platform: "windows-latest"
            target: "x86_64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lock

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: ./apps/core
          tauriScript: bunx tauri
          includeRelease: false
          includeDebug: true
          args: --target ${{matrix.target}} ${{ matrix.target == 'aarch64-pc-windows-msvc' && '--bundles nsis' || ''}}
